name: npm audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.7.3
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: amcalabretta
          issue_labels: vulnerability
          dedupe_issues: true
