name: dependency check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install depcheck
        run: npm install depcheck -g
      - name: check on dependencies 
        run: depcheck --ignores="eslint,nyc,eslint-plugin-import"
