name: Update documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # Name the Job
    name: Prepare
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Prepare mkdocs
        run: |
          pip install mkdocs
    name: Run mkdocs      
    steps:
      - name: create website
        run: |
          mkdocs build
