name: unit testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install mocha
        run: npm install mocha -g
      - name: run test
        run: npm run test
